export const CAMPUSES = [
  {
    id: 'rvr-jc',
    name: 'RVR & JC',
    fullName: 'R.V.R. & J.C. College of Engineering',
    city: 'Guntur, AP',
    shortCode: 'RVR&JC',
    hostels: ['Main Canteen', 'Central Library', 'Main Gate', 'CSE Dept', 'Boys Hostel', 'Girls Hostel', 'PG Annex']
  },
  {
    id: 'rit-chennai',
    name: 'RIT Chennai',
    fullName: 'Riverside Institute of Technology',
    city: 'Chennai, TN',
    shortCode: 'RIT',
    hostels: ['Main Canteen', 'Library Block', 'Main Gate', 'CSE Dept', 'Ganga Hostel', 'Cauvery Hostel', 'New PG']
  },
  {
    id: 'vki-pune',
    name: 'VKI Pune',
    fullName: 'Valley Knowledge Institute',
    city: 'Pune, MH',
    shortCode: 'VKI',
    hostels: ['Central Square', 'Library Plaza', 'Main Gate', 'East Block', 'West Block', 'PG Annex']
  },
  {
    id: 'hce-mumbai',
    name: 'HCE Mumbai',
    fullName: 'Harbor College of Engineering',
    city: 'Mumbai, MH',
    shortCode: 'HCE',
    hostels: ['Quadrangle', 'Canteen Area', 'Marine Gate', 'Harbour A', 'Harbour B', 'Marine PG']
  }
];

export const CATEGORIES = [
  {
    id: 'books-notes',
    name: 'Books & Notes',
    blurb: 'Textbooks, GATE guides, end-sem handwritten notes & PYQs',
    kind: 'marketplace',
    icon: 'BookOpen',
    image: 'https://images.unsplash.com/photo-1497633762265-9d179a990aa6?auto=format&fit=crop&w=600&q=80'
  },
  {
    id: 'calci-drafters',
    name: 'Calci & Drafters',
    blurb: 'Casio Classwiz calculators, mini drafters, engineering drawing tools',
    kind: 'marketplace',
    icon: 'Calculator',
    image: 'https://images.unsplash.com/photo-1611125832047-1d7ad1e8e48b?auto=format&fit=crop&w=600&q=80'
  },
  {
    id: 'laptops-gadgets',
    name: 'Laptops & Gadgets',
    blurb: 'Laptops, monitors, keyboards, mice, cooling pads & tech accessories',
    kind: 'marketplace',
    icon: 'Laptop',
    image: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=600&q=80'
  },
  {
    id: 'phones',
    name: 'Phones & Audio',
    blurb: 'Smartphones, TWS earbuds, Bluetooth speakers & powerbanks',
    kind: 'marketplace',
    icon: 'Smartphone',
    image: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=600&q=80'
  },
  {
    id: 'cycles',
    name: 'Cycles & Transport',
    blurb: 'Geared & non-geared campus bicycles, helmets & locks',
    kind: 'marketplace',
    icon: 'Bike',
    image: 'https://images.unsplash.com/photo-1485965120184-e220f721d03e?auto=format&fit=crop&w=600&q=80'
  },
  {
    id: 'furniture',
    name: 'Furniture',
    blurb: 'Study tables, ergonomics chairs, bookshelves, bean bags',
    kind: 'marketplace',
    icon: 'Armchair',
    image: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=600&q=80'
  },
  {
    id: 'hostel-essentials',
    name: 'Hostel Essentials',
    blurb: 'Kettles, fans, extension boards, irons, mattresses & buckets',
    kind: 'marketplace',
    icon: 'Coffee',
    image: 'https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&w=600&q=80'
  },
  {
    id: 'fashion',
    name: 'Fashion & Uniforms',
    blurb: 'Lab coats, placement formal suits, hoodies & footwear',
    kind: 'marketplace',
    icon: 'Shirt',
    image: 'https://images.unsplash.com/photo-1523381210434-271e8be1f52b?auto=format&fit=crop&w=600&q=80'
  },
  {
    id: 'sports-hobbies',
    name: 'Sports & Hobbies',
    blurb: 'Badminton rackets, footballs, cricket gear, guitars & board games',
    kind: 'marketplace',
    icon: 'Trophy',
    image: 'https://images.unsplash.com/photo-1517649763962-0c623266010b?auto=format&fit=crop&w=600&q=80'
  },
  {
    id: 'roommates',
    name: 'Roommate Finder',
    blurb: 'Hostel room swaps, PG flatmates & occupancy replacements',
    kind: 'roommate',
    icon: 'Users',
    image: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=600&q=80'
  },
  {
    id: 'lost-found',
    name: 'Lost & Found',
    blurb: 'Lost ID cards, keys, earbuds, drafter covers & found items',
    kind: 'lostfound',
    icon: 'Search',
    image: 'https://images.unsplash.com/photo-1584438784894-089d6a62b8fa?auto=format&fit=crop&w=600&q=80'
  },
  {
    id: 'tutoring-services',
    name: 'Tutoring & Services',
    blurb: 'Maths backlog tutoring, CAD project help, report drafting, code debug',
    kind: 'service',
    icon: 'GraduationCap',
    image: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=600&q=80'
  }
];

export const INITIAL_USERS = [
  {
    id: 'u1',
    name: 'Aarav Sharma',
    email: 'aarav.sharma@rit.edu.in',
    hostel: 'Ganga Hostel',
    student_type: 'Hosteller',
    campus: 'rit-chennai',
    year: '3rd Year CSE',
    avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=150&q=80',
    verified: true
  },
  {
    id: 'u2',
    name: 'Priya Sundaram',
    email: 'priya.s@rit.edu.in',
    hostel: 'Main Canteen / CSE Dept',
    student_type: 'Day Scholar',
    campus: 'rit-chennai',
    year: '4th Year ECE',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=150&q=80',
    verified: true
  },
  {
    id: 'u3',
    name: 'Rohan Kulkarni',
    email: 'rohan.k@vki.ac.in',
    hostel: 'Library Plaza',
    student_type: 'Day Scholar',
    campus: 'vki-pune',
    year: '2nd Year Mech',
    avatar: 'https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?auto=format&fit=crop&w=150&q=80',
    verified: true
  },
  {
    id: 'u4',
    name: 'Ananya Mehta',
    email: 'ananya.m@hce.ac.in',
    hostel: 'Marine PG',
    student_type: 'PG Resident',
    campus: 'hce-mumbai',
    year: '3rd Year IT',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=150&q=80',
    verified: true
  }
];

export const SEED_LISTINGS = [
  // --- R.V.R. & J.C. COLLEGE OF ENGINEERING LISTINGS ---
  {
    id: 'rvr-01',
    user_id: 'u1',
    title: 'Casio FX-991CW Classwiz Scientific Calculator (Mint Condition)',
    description: 'Selling my Casio FX-991CW Classwiz solar scientific calculator. Essential for Matrix calculations, Differential Equations, and Integration in RVR&JC B.Tech exams. Protective lid intact, clean display.',
    price: 900,
    price_label: '₹ 900',
    category: 'calci-drafters',
    condition: 'Like new',
    campus: 'rvr-jc',
    hostel: 'Central Library',
    city: 'Guntur, AP',
    image_url: 'https://images.unsplash.com/photo-1611125832047-1d7ad1e8e48b?auto=format&fit=crop&w=800&q=80',
    featured: true,
    listing_kind: 'marketplace',
    extra: { brand: 'Casio', model: 'FX-991CW' },
    seller_label: 'Anil P. (3rd Yr CSE)',
    verified: true,
    views: 185,
    created_at: '1 hour ago'
  },
  {
    id: 'rvr-02',
    user_id: 'u2',
    title: 'Omega Engineering Mini Drafter with Carrying Bag + Sheet Clips',
    description: 'Required for 1st Year Engineering Drawing & CAD lab at RVR&JC. Perfect 90-degree alignment, unbreakable steel arms, zero cracks. Includes protective shoulder bag.',
    price: 450,
    price_label: '₹ 450',
    category: 'calci-drafters',
    condition: 'Good',
    campus: 'rvr-jc',
    hostel: 'Main Canteen',
    city: 'Guntur, AP',
    image_url: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=800&q=80',
    featured: true,
    listing_kind: 'marketplace',
    extra: { brand: 'Omega' },
    seller_label: 'Suresh V. (2nd Yr Mech)',
    verified: true,
    views: 110,
    created_at: '3 hours ago'
  },
  {
    id: 'rvr-03',
    user_id: 'u1',
    title: 'Higher Engineering Mathematics - B.S. Grewal (44th Edition)',
    description: 'Standard textbook for M1, M2, M3, M4 modules. Clear print, no missing pages, includes previous GATE solved papers and formula cheatsheet.',
    price: 380,
    price_label: '₹ 380',
    category: 'books-notes',
    condition: 'Good',
    campus: 'rvr-jc',
    hostel: 'CSE Dept',
    city: 'Guntur, AP',
    image_url: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=800&q=80',
    featured: true,
    listing_kind: 'marketplace',
    extra: { author: 'B.S. Grewal', edition: '44th' },
    seller_label: 'Anil P. (3rd Yr CSE)',
    verified: true,
    views: 220,
    created_at: '4 hours ago'
  },
  {
    id: 'rvr-04',
    user_id: 'u3',
    title: 'Pigeon 1.5 Litre Stainless Steel Electric Kettle',
    description: 'Essential for hostel room late night Maggi, tea & coffee. Rapid boiling, automatic shutoff, cordless pouring base. Used 1 semester.',
    price: 490,
    price_label: '₹ 490',
    category: 'hostel-essentials',
    condition: 'Like new',
    campus: 'rvr-jc',
    hostel: 'Boys Hostel',
    city: 'Guntur, AP',
    image_url: 'https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&w=800&q=80',
    featured: true,
    listing_kind: 'marketplace',
    extra: { brand: 'Pigeon', capacity: '1.5L' },
    seller_label: 'Kiran R. (4th Yr ECE)',
    verified: true,
    views: 190,
    created_at: '4 hours ago'
  },
  {
    id: 'rvr-05',
    user_id: 'u4',
    title: 'Logitech G213 Prodigy RGB Gaming Keyboard',
    description: 'Tactile Mech-Dome keys, anti-ghosting, RGB illumination, spill resistant. Perfect for coding, project work, and gaming at RVR&JC hostels.',
    price: 1400,
    price_label: '₹ 1,400',
    category: 'laptops-gadgets',
    condition: 'Like new',
    campus: 'rvr-jc',
    hostel: 'CSE Dept',
    city: 'Guntur, AP',
    image_url: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=800&q=80',
    featured: true,
    listing_kind: 'marketplace',
    extra: { brand: 'Logitech', model: 'G213' },
    seller_label: 'Bhavya M. (3rd Yr IT)',
    verified: true,
    views: 230,
    created_at: '12 hours ago'
  },
  {
    id: 'rvr-06',
    user_id: 'u3',
    title: 'Hero Sprint 21-Speed Gear Bicycle (Ideal for Campus Transport)',
    description: 'Smooth gear shift, front suspension, dual disc brakes, new tyres fitted. Perfect for commuting between Guntur hostels, canteen, and RVR&JC main gate.',
    price: 3200,
    price_label: '₹ 3,200',
    category: 'cycles',
    condition: 'Good',
    campus: 'rvr-jc',
    hostel: 'Main Gate',
    city: 'Guntur, AP',
    image_url: 'https://images.unsplash.com/photo-1485965120184-e220f721d03e?auto=format&fit=crop&w=800&q=80',
    featured: true,
    listing_kind: 'marketplace',
    extra: { brand: 'Hero', gears: '21 Speed' },
    seller_label: 'Kiran R. (4th Yr ECE)',
    verified: true,
    views: 310,
    created_at: '6 hours ago'
  },
  {
    id: 'rvr-07',
    user_id: 'u4',
    title: 'HP 15s Ryzen 5 Laptop (8GB RAM / 512GB SSD / Windows 11)',
    description: 'Super fast laptop for coding, MATLAB, AutoCAD, and Web Development. Battery backup 4+ hours, original HP charger & laptop sleeve included.',
    price: 26500,
    price_label: '₹ 26,500',
    category: 'laptops-gadgets',
    condition: 'Like new',
    campus: 'rvr-jc',
    hostel: 'Central Library',
    city: 'Guntur, AP',
    image_url: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=800&q=80',
    featured: true,
    listing_kind: 'marketplace',
    extra: { brand: 'HP', specs: 'Ryzen 5 / 8GB / 512GB SSD' },
    seller_label: 'Bhavya M. (3rd Yr IT)',
    verified: true,
    views: 450,
    created_at: '1 day ago'
  },
  {
    id: 'rvr-08',
    user_id: 'u2',
    title: 'White Cotton Lab Coat / Apron (Size L) - Workshop & Chemistry Lab',
    description: 'Clean white lab apron with double front pockets. Mandatory for 1st Year Chemistry, Workshop, and Materials Testing labs at RVR&JC.',
    price: 200,
    price_label: '₹ 200',
    category: 'hostel-essentials',
    condition: 'Like new',
    campus: 'rvr-jc',
    hostel: 'Boys Hostel',
    city: 'Guntur, AP',
    image_url: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=800&q=80',
    featured: false,
    listing_kind: 'marketplace',
    extra: { size: 'Large' },
    seller_label: 'Suresh V. (2nd Yr Mech)',
    verified: true,
    views: 95,
    created_at: '1 day ago'
  },
  {
    id: 'rvr-09',
    user_id: 'u1',
    title: 'BOAT Airdopes 141 TWS Earbuds (Black Case) - Long Battery Backup',
    description: 'BoAt TWS earbuds with type-C fast charging case. 42 hours total playtime, crisp bass, clear mic quality for online classes & GATE lectures.',
    price: 850,
    price_label: '₹ 850',
    category: 'phones',
    condition: 'Like new',
    campus: 'rvr-jc',
    hostel: 'Main Canteen',
    city: 'Guntur, AP',
    image_url: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?auto=format&fit=crop&w=800&q=80',
    featured: false,
    listing_kind: 'marketplace',
    extra: { brand: 'boAt', model: 'Airdopes 141' },
    seller_label: 'Anil P. (3rd Yr CSE)',
    verified: true,
    views: 140,
    created_at: '2 days ago'
  },
  {
    id: 'rvr-10',
    user_id: 'u3',
    title: 'Roommate Wanted — 2BHK Flat near R.V.R. & J.C. College Gate',
    description: 'Looking for 1 male engineering student to share 2BHK PG flat within walking distance of RVR&JC main gate. 24/7 water supply, Wi-Fi, bike parking.',
    price: 3500,
    price_label: '₹ 3,500 / month',
    category: 'roommates',
    condition: 'Like new',
    campus: 'rvr-jc',
    hostel: 'PG Annex',
    city: 'Guntur, AP',
    image_url: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=800&q=80',
    featured: true,
    listing_kind: 'roommate',
    extra: { occupancy: 'Single Room', gender: 'Male' },
    seller_label: 'Kiran R. (4th Yr ECE)',
    verified: true,
    views: 280,
    created_at: '2 days ago'
  },
  {
    id: 'rvr-11',
    user_id: 'u4',
    title: 'LOST: RVR & JC College ID Card (Reg: 211421104085) near Library',
    description: 'Lost my R.V.R. & J.C. student ID card with blue lanyard near Central Library reading hall today afternoon. Please return if found!',
    price: 0,
    price_label: 'LOST ITEM',
    category: 'lost-found',
    condition: 'Fair',
    campus: 'rvr-jc',
    hostel: 'Central Library',
    city: 'Guntur, AP',
    image_url: 'https://images.unsplash.com/photo-1584438784894-089d6a62b8fa?auto=format&fit=crop&w=800&q=80',
    featured: true,
    listing_kind: 'lostfound',
    extra: { status: 'LOST', item: 'Student ID Card' },
    seller_label: 'Bhavya M. (3rd Yr IT)',
    verified: true,
    views: 160,
    created_at: '5 hours ago'
  },
  {
    id: 'rvr-12',
    user_id: 'u1',
    title: 'Peer Tutoring: Data Structures & Algorithms / C++ Backlog Prep',
    description: 'One-on-one tutoring for RVR&JC CSE/ECE/IT students preparing for mid-sem, end-sem, and lab exams. Solved previous year papers provided.',
    price: 300,
    price_label: '₹ 300 / hr',
    category: 'tutoring-services',
    condition: 'Like new',
    campus: 'rvr-jc',
    hostel: 'Central Library',
    city: 'Guntur, AP',
    image_url: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=800&q=80',
    featured: true,
    listing_kind: 'service',
    extra: { subject: 'DSA & C++', rate: '₹300/hr' },
    seller_label: 'Anil P. (3rd Yr CSE)',
    verified: true,
    views: 310,
    created_at: '2 days ago'
  },

  // --- RIT CHENNAI LISTINGS ---
  {
    id: 'rit-01',
    user_id: 'u1',
    title: 'Casio FX-991EX Classwiz Scientific Calculator (Mint Condition)',
    description: 'Selling my Casio FX-991EX Classwiz solar calculator. Super handy for Matrix operations, Integration, and Differential Equations. Battery holds charge, display clean, protective lid included.',
    price: 950,
    price_label: '₹ 950',
    category: 'calci-drafters',
    condition: 'Like new',
    campus: 'rit-chennai',
    hostel: 'Ganga',
    city: 'Chennai, TN',
    image_url: 'https://images.unsplash.com/photo-1611125832047-1d7ad1e8e48b?auto=format&fit=crop&w=800&q=80',
    featured: true,
    listing_kind: 'marketplace',
    extra: { brand: 'Casio', model: 'FX-991EX' },
    seller_label: 'Aarav S. (3rd Yr CSE)',
    verified: true,
    views: 142,
    created_at: '2 hours ago'
  },
  {
    id: 'rit-02',
    user_id: 'u2',
    title: 'Omega Mini Drafter with Carrying Bag + Sheet Holder',
    description: 'Essential for 1st Year Engineering Graphics / CAD drawing lab. Zero alignment issue, brass clips intact, no cracks on scale. Used for 1 semester only.',
    price: 450,
    price_label: '₹ 450',
    category: 'calci-drafters',
    condition: 'Good',
    campus: 'rit-chennai',
    hostel: 'Cauvery',
    city: 'Chennai, TN',
    image_url: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=800&q=80',
    featured: true,
    listing_kind: 'marketplace',
    extra: { brand: 'Omega' },
    seller_label: 'Priya S. (4th Yr ECE)',
    verified: true,
    views: 89,
    created_at: '5 hours ago'
  },
  {
    id: 'rit-03',
    user_id: 'u1',
    title: 'Higher Engineering Mathematics - BS Grewal 44th Edition',
    description: 'Must-have book for M1, M2, and M3 end-sem exams. Clean pages, no ink scribbles, zero torn pages. Includes answer keys and solved gate questions.',
    price: 380,
    price_label: '₹ 380',
    category: 'books-notes',
    condition: 'Good',
    campus: 'rit-chennai',
    hostel: 'Ganga',
    city: 'Chennai, TN',
    image_url: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=800&q=80',
    featured: true,
    listing_kind: 'marketplace',
    extra: { author: 'B.S. Grewal', edition: '44th' },
    seller_label: 'Aarav S. (3rd Yr CSE)',
    verified: true,
    views: 210,
    created_at: '1 day ago'
  },
  {
    id: 'rit-04',
    user_id: 'u2',
    title: 'Hero Hawk 21-Speed Gear Bicycle (Red & Black)',
    description: 'Perfect for riding from Ganga Hostel to Library & Main Gate. Shimano 21-speed gears, front suspension working great, new rear tire fitted last month. Comes with heavy lock & key.',
    price: 3200,
    price_label: '₹ 3,200',
    category: 'cycles',
    condition: 'Good',
    campus: 'rit-chennai',
    hostel: 'Yamuna',
    city: 'Chennai, TN',
    image_url: 'https://images.unsplash.com/photo-1485965120184-e220f721d03e?auto=format&fit=crop&w=800&q=80',
    featured: false,
    listing_kind: 'marketplace',
    extra: { gears: '21 Speed', color: 'Red/Black' },
    seller_label: 'Karthik V. (2nd Yr Mech)',
    verified: true,
    views: 315,
    created_at: '3 hours ago'
  },
  {
    id: 'rit-05',
    user_id: 'u1',
    title: 'Pigeon 1.5 Litre Stainless Steel Electric Kettle',
    description: 'Life savior for late night maggi, tea, coffee, and soup during end-sem exams! Auto shut-off working, clean interior, 1.5m power cord included.',
    price: 490,
    price_label: '₹ 490',
    category: 'hostel-essentials',
    condition: 'Like new',
    campus: 'rit-chennai',
    hostel: 'Ganga',
    city: 'Chennai, TN',
    image_url: 'https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&w=800&q=80',
    featured: true,
    listing_kind: 'marketplace',
    extra: { power: '1500W', capacity: '1.5L' },
    seller_label: 'Aarav S. (3rd Yr CSE)',
    verified: true,
    views: 180,
    created_at: '4 hours ago'
  },
  {
    id: 'rit-06',
    user_id: 'u2',
    title: 'Nilkamal Plastic Study Chair + Wooden Folding Bed Table',
    description: 'Selling study chair and adjustable bed laptop table together. Comfortable back support for study sessions. Table has cup holder and tablet slot.',
    price: 750,
    price_label: '₹ 750',
    category: 'furniture',
    condition: 'Good',
    campus: 'rit-chennai',
    hostel: 'Cauvery',
    city: 'Chennai, TN',
    image_url: 'https://images.unsplash.com/photo-1580481072645-022f9a6d83d0?auto=format&fit=crop&w=800&q=80',
    featured: false,
    listing_kind: 'marketplace',
    extra: { material: 'Polypropylene & Engineered Wood' },
    seller_label: 'Priya S. (4th Yr ECE)',
    verified: true,
    views: 95,
    created_at: '6 hours ago'
  },
  {
    id: 'rit-07',
    user_id: 'u1',
    title: 'Yonex Muscle Power 29 Badminton Racket + 3 Mavis 350 Shuttles',
    description: 'Strung at 24 lbs BG65. Balanced racket ideal for hostel court matches. Including 3 yellow nylon shuttlecocks.',
    price: 850,
    price_label: '₹ 850',
    category: 'sports-hobbies',
    condition: 'Like new',
    campus: 'rit-chennai',
    hostel: 'Krishna',
    city: 'Chennai, TN',
    image_url: 'https://images.unsplash.com/photo-1626224583764-f87db24ac4ea?auto=format&fit=crop&w=800&q=80',
    featured: false,
    listing_kind: 'marketplace',
    extra: { brand: 'Yonex' },
    seller_label: 'Sanjay M. (3rd Yr EEE)',
    verified: false,
    views: 120,
    created_at: '1 day ago'
  },
  {
    id: 'rit-08',
    user_id: 'u2',
    title: 'White Lab Coat Size L (Clean & Pressed)',
    description: 'Mandatory for Chemistry and Workshop labs. Pure cotton, zero stains, washed and pressed. Pocket stitched properly.',
    price: 180,
    price_label: '₹ 180',
    category: 'fashion',
    condition: 'Good',
    campus: 'rit-chennai',
    hostel: 'Cauvery',
    city: 'Chennai, TN',
    image_url: 'https://images.unsplash.com/photo-1584036561566-baf8f5f1b144?auto=format&fit=crop&w=800&q=80',
    featured: false,
    listing_kind: 'marketplace',
    extra: { size: 'L', material: '100% Cotton' },
    seller_label: 'Priya S. (4th Yr ECE)',
    verified: true,
    views: 64,
    created_at: '2 days ago'
  },
  {
    id: 'rit-09',
    user_id: 'u1',
    title: 'Logitech G213 Prodigy RGB Gaming Keyboard',
    description: 'Mecha-dome keys with dedicated media controls and customizable 5-zone RGB lighting. Spill-resistant design. Great condition.',
    price: 1400,
    price_label: '₹ 1,400',
    category: 'laptops-gadgets',
    condition: 'Like new',
    campus: 'rit-chennai',
    hostel: 'Ganga',
    city: 'Chennai, TN',
    image_url: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=800&q=80',
    featured: true,
    listing_kind: 'marketplace',
    extra: { brand: 'Logitech', RGB: 'Yes' },
    seller_label: 'Aarav S. (3rd Yr CSE)',
    verified: true,
    views: 240,
    created_at: '12 hours ago'
  },
  {
    id: 'rit-10',
    user_id: 'u2',
    title: 'Need 1 Male Roommate - Ganga Hostel AC Room (3rd Floor)',
    description: 'Our roommate transferred colleges. Looking for a non-smoker 2nd/3rd year student to share 3-sharing AC room in Ganga hostel. Room has attached bathroom, study table, balcony view facing sports ground.',
    price: 3500,
    price_label: '₹ 3,500 / month',
    category: 'roommates',
    condition: 'Good',
    campus: 'rit-chennai',
    hostel: 'Ganga',
    city: 'Chennai, TN',
    image_url: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=800&q=80',
    featured: true,
    listing_kind: 'roommate',
    extra: { occupancy: '3 Sharing AC', mess: 'Included in hostel fee', gender: 'Male' },
    seller_label: 'Deepak R. (3rd Yr Mech)',
    verified: true,
    views: 450,
    created_at: '1 day ago'
  },
  {
    id: 'rit-11',
    user_id: 'u1',
    title: 'LOST: RIT College ID Card (Roll No: 21CS042 - Aarav Sharma)',
    description: 'Lost my official student ID card with blue lanyard somewhere between Library 2nd floor and Mess Hall near Ganga hostel yesterday around 5 PM. If found please ping me urgently!',
    price: 0,
    price_label: 'LOST ITEM',
    category: 'lost-found',
    condition: 'Fair',
    campus: 'rit-chennai',
    hostel: 'Ganga',
    city: 'Chennai, TN',
    image_url: 'https://images.unsplash.com/photo-1584438784894-089d6a62b8fa?auto=format&fit=crop&w=800&q=80',
    featured: true,
    listing_kind: 'lostfound',
    extra: { status: 'LOST', item: 'College ID Card', location: 'Near Library / Mess' },
    seller_label: 'Aarav S. (3rd Yr CSE)',
    verified: true,
    views: 610,
    created_at: '1 day ago'
  },
  {
    id: 'rit-12',
    user_id: 'u2',
    title: 'Peer Tutoring: Data Structures & Algorithms / C++ Backlog Prep',
    description: 'Struggling with Trees, Graphs, Dynamic Programming, or pointers? 4th year CSE student offering 1-on-1 tutoring sessions at Library study room. Solved 500+ LeetCode problems.',
    price: 300,
    price_label: '₹ 300 / hr',
    category: 'tutoring-services',
    condition: 'Brand new',
    campus: 'rit-chennai',
    hostel: 'Cauvery',
    city: 'Chennai, TN',
    image_url: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=800&q=80',
    featured: true,
    listing_kind: 'service',
    extra: { subject: 'DSA & C++', mode: 'In-person @ Library' },
    seller_label: 'Priya S. (4th Yr ECE)',
    verified: true,
    views: 380,
    created_at: '2 days ago'
  },
  {
    id: 'rit-13',
    user_id: 'u1',
    title: 'Crompton 16-inch Pedestal High-Speed Oscillating Fan',
    description: 'High speed 400mm fan with 3 speed controls and height adjustment. Essential for Chennai summer! Smooth motor operation.',
    price: 900,
    price_label: '₹ 900',
    category: 'hostel-essentials',
    condition: 'Good',
    campus: 'rit-chennai',
    hostel: 'New PG',
    city: 'Chennai, TN',
    image_url: 'https://images.unsplash.com/photo-1618941723380-0a56247c43df?auto=format&fit=crop&w=800&q=80',
    featured: false,
    listing_kind: 'marketplace',
    extra: { brand: 'Crompton' },
    seller_label: 'Vikram N. (2nd Yr Civil)',
    verified: false,
    views: 110,
    created_at: '2 days ago'
  },

  // --- VKI PUNE LISTINGS ---
  {
    id: 'vki-01',
    user_id: 'u3',
    title: 'Casio FX-82MS 2nd Gen Scientific Calculator',
    description: 'Ideal calculator for 1st & 2nd year Mechanical & Civil engineering courses. 2-line display, 240 functions. Clean condition with slide cover.',
    price: 450,
    price_label: '₹ 450',
    category: 'calci-drafters',
    condition: 'Like new',
    campus: 'vki-pune',
    hostel: 'East Block',
    city: 'Pune, MH',
    image_url: 'https://images.unsplash.com/photo-1594980596870-8aa52a78d8cd?auto=format&fit=crop&w=800&q=80',
    featured: true,
    listing_kind: 'marketplace',
    extra: { brand: 'Casio' },
    seller_label: 'Rohan K. (2nd Yr Mech)',
    verified: true,
    views: 155,
    created_at: '1 hour ago'
  },
  {
    id: 'vki-02',
    user_id: 'u3',
    title: 'Firefox Target 27.5T 21-Speed Alloy Mountain Bike',
    description: 'Lightweight aluminium alloy frame, Zoom front suspension, disc brakes front and rear. Smooth gear shifting. Perfect for riding around VKI Pune hilly campus.',
    price: 5800,
    price_label: '₹ 5,800',
    category: 'cycles',
    condition: 'Like new',
    campus: 'vki-pune',
    hostel: 'West Block',
    city: 'Pune, MH',
    image_url: 'https://images.unsplash.com/photo-1532298229144-0ec0c57515c7?auto=format&fit=crop&w=800&q=80',
    featured: true,
    listing_kind: 'marketplace',
    extra: { brand: 'Firefox', frame: 'Alloy' },
    seller_label: 'Tanmay P. (3rd Yr ENTC)',
    verified: true,
    views: 290,
    created_at: '4 hours ago'
  },
  {
    id: 'vki-03',
    user_id: 'u3',
    title: 'GATE CSE 2025 Complete Ace Academy + Made Easy Postal Notes',
    description: 'Complete set of spiral-bound subject wise notes for GATE CS/IT. Includes Operating Systems, DBMS, Theory of Computation, Algorithms, Computer Networks, and Compiler Design.',
    price: 1200,
    price_label: '₹ 1,200',
    category: 'books-notes',
    condition: 'Good',
    campus: 'vki-pune',
    hostel: 'East Block',
    city: 'Pune, MH',
    image_url: 'https://images.unsplash.com/photo-1497633762265-9d179a990aa6?auto=format&fit=crop&w=800&q=80',
    featured: true,
    listing_kind: 'marketplace',
    extra: { exam: 'GATE CSE', institute: 'Ace & Made Easy' },
    seller_label: 'Rohan K. (2nd Yr Mech)',
    verified: true,
    views: 410,
    created_at: '1 day ago'
  },
  {
    id: 'vki-04',
    user_id: 'u3',
    title: 'Realme Buds Air 3 TWS (Active Noise Cancellation - Blue)',
    description: '42dB Active Noise Cancellation, 30 hours total playback time, 10mm bass boost drivers. Clean case, replaced silicone tips included.',
    price: 1250,
    price_label: '₹ 1,250',
    category: 'phones',
    condition: 'Like new',
    campus: 'vki-pune',
    hostel: 'Lakeview',
    city: 'Pune, MH',
    image_url: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?auto=format&fit=crop&w=800&q=80',
    featured: false,
    listing_kind: 'marketplace',
    extra: { brand: 'Realme', ANC: '42dB' },
    seller_label: 'Aditya S. (4th Yr Comp)',
    verified: false,
    views: 175,
    created_at: '6 hours ago'
  },
  {
    id: 'vki-05',
    user_id: 'u3',
    title: 'SolidWorks 3D Modeling & CAD Project Help',
    description: 'Mechanical / Production Engineering students needing 3D CAD models, assembly drawings, or FEA simulation for mini project or lab report. Quick turnaround.',
    price: 500,
    price_label: '₹ 500 / project',
    category: 'tutoring-services',
    condition: 'Brand new',
    campus: 'vki-pune',
    hostel: 'East Block',
    city: 'Pune, MH',
    image_url: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=800&q=80',
    featured: true,
    listing_kind: 'service',
    extra: { software: 'SolidWorks / AutoCAD' },
    seller_label: 'Rohan K. (2nd Yr Mech)',
    verified: true,
    views: 320,
    created_at: '2 days ago'
  },
  {
    id: 'vki-06',
    user_id: 'u3',
    title: 'FOUND: Black Casio FX-991ES Plus Calci near Lakeview Canteen',
    description: 'Found a Casio calculator lying on the wooden bench near Lakeview Canteen today afternoon. Has a small Batman sticker on back lid. Owner can claim by verifying details.',
    price: 0,
    price_label: 'FOUND ITEM',
    category: 'lost-found',
    condition: 'Good',
    campus: 'vki-pune',
    hostel: 'Lakeview',
    city: 'Pune, MH',
    image_url: 'https://images.unsplash.com/photo-1611125832047-1d7ad1e8e48b?auto=format&fit=crop&w=800&q=80',
    featured: true,
    listing_kind: 'lostfound',
    extra: { status: 'FOUND', item: 'Casio Calculator', location: 'Lakeview Canteen' },
    seller_label: 'Shardul V. (3rd Yr IT)',
    verified: true,
    views: 280,
    created_at: '5 hours ago'
  },
  {
    id: 'vki-07',
    user_id: 'u3',
    title: '2BHK PG Flatmate Wanted - Near VKI Gate 2 (Fully Furnished)',
    description: 'Single private room available in a spacious 2BHK flat just 200m from VKI Gate 2. Fridge, washing machine, WiFi, high-speed power backup available. Maid for cooking & cleaning.',
    price: 5500,
    price_label: '₹ 5,500 / month',
    category: 'roommates',
    condition: 'Like new',
    campus: 'vki-pune',
    hostel: 'PG Annex',
    city: 'Pune, MH',
    image_url: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=800&q=80',
    featured: true,
    listing_kind: 'roommate',
    extra: { occupancy: 'Private Room', gender: 'Male/Female' },
    seller_label: 'Rohan K. (2nd Yr Mech)',
    verified: true,
    views: 520,
    created_at: '3 days ago'
  },
  {
    id: 'vki-08',
    user_id: 'u3',
    title: 'Wakefit Orthopedic Dual Comfort Mattress (6x3 ft Single Bed)',
    description: '6 inches thickness memory foam mattress. Fits standard hostel cot perfectly. Super clean with removable washable cover.',
    price: 1800,
    price_label: '₹ 1,800',
    category: 'hostel-essentials',
    condition: 'Good',
    campus: 'vki-pune',
    hostel: 'West Block',
    city: 'Pune, MH',
    image_url: 'https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?auto=format&fit=crop&w=800&q=80',
    featured: false,
    listing_kind: 'marketplace',
    extra: { brand: 'Wakefit', dimensions: '6x3 ft' },
    seller_label: 'Saurabh B. (4th Yr Chem)',
    verified: false,
    views: 140,
    created_at: '1 day ago'
  },

  // --- HCE MUMBAI LISTINGS ---
  {
    id: 'hce-01',
    user_id: 'u4',
    title: 'Dell Inspiron 15 (11th Gen i5, 16GB RAM, 512GB SSD, FHD)',
    description: 'Ideal laptop for coding, Android Studio, SolidWorks, and project work. Smooth performance, battery lasts 4+ hours, original charger included.',
    price: 28500,
    price_label: '₹ 28,500',
    category: 'laptops-gadgets',
    condition: 'Like new',
    campus: 'hce-mumbai',
    hostel: 'Harbour A',
    city: 'Mumbai, MH',
    image_url: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=800&q=80',
    featured: true,
    listing_kind: 'marketplace',
    extra: { brand: 'Dell', processor: 'Core i5 11th Gen', RAM: '16GB' },
    seller_label: 'Ananya M. (3rd Yr IT)',
    verified: true,
    views: 680,
    created_at: '3 hours ago'
  },
  {
    id: 'hce-02',
    user_id: 'u4',
    title: 'Redmi Note 12 Pro 5G (8GB / 256GB - Frosted Blue)',
    description: '120Hz AMOLED display, Sony IMX766 OIS camera, 67W fast charging. Box, bill, and original charger available.',
    price: 11200,
    price_label: '₹ 11,200',
    category: 'phones',
    condition: 'Like new',
    campus: 'hce-mumbai',
    hostel: 'Harbour A',
    city: 'Mumbai, MH',
    image_url: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=800&q=80',
    featured: true,
    listing_kind: 'marketplace',
    extra: { brand: 'Xiaomi / Redmi', storage: '256GB' },
    seller_label: 'Ananya M. (3rd Yr IT)',
    verified: true,
    views: 390,
    created_at: '7 hours ago'
  },
  {
    id: 'hce-03',
    user_id: 'u4',
    title: 'Mini Drafter + Engineering Drawing Tool Set (HCE Approved)',
    description: 'Complete kit including mini drafter, set squares, protractor, compass set, stencil, and drafting tube holder. Perfect for 1st Year FE students.',
    price: 520,
    price_label: '₹ 520',
    category: 'calci-drafters',
    condition: 'Good',
    campus: 'hce-mumbai',
    hostel: 'Harbour B',
    city: 'Mumbai, MH',
    image_url: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=800&q=80',
    featured: false,
    listing_kind: 'marketplace',
    extra: { brand: 'Isomars' },
    seller_label: 'Nikhil G. (2nd Yr EXTC)',
    verified: false,
    views: 105,
    created_at: '4 hours ago'
  },
  {
    id: 'hce-04',
    user_id: 'u4',
    title: 'Raymond Navy Blue Placement Formal Suit (Blazer + Trousers - Size 38)',
    description: 'Tailored navy blue suit worn only twice during campus placement interviews. Dry cleaned and ready for upcoming TPO placement season.',
    price: 2400,
    price_label: '₹ 2,400',
    category: 'fashion',
    condition: 'Like new',
    campus: 'hce-mumbai',
    hostel: 'Harbour A',
    city: 'Mumbai, MH',
    image_url: 'https://images.unsplash.com/photo-1594938298603-c8148c4dae35?auto=format&fit=crop&w=800&q=80',
    featured: true,
    listing_kind: 'marketplace',
    extra: { brand: 'Raymond', size: '38 Regular' },
    seller_label: 'Ananya M. (3rd Yr IT)',
    verified: true,
    views: 260,
    created_at: '1 day ago'
  },
  {
    id: 'hce-05',
    user_id: 'u4',
    title: 'Hertz HZA-400 Acoustic Guitar + Padded Gig Bag',
    description: 'Beautiful warm tone acoustic guitar. Low string action makes it easy on fingers. Strings tuned and fresh. Comes with bag and picks.',
    price: 2900,
    price_label: '₹ 2,900',
    category: 'sports-hobbies',
    condition: 'Good',
    campus: 'hce-mumbai',
    hostel: 'Marine PG',
    city: 'Mumbai, MH',
    image_url: 'https://images.unsplash.com/photo-1510915361894-db8b60106cb1?auto=format&fit=crop&w=800&q=80',
    featured: true,
    listing_kind: 'marketplace',
    extra: { brand: 'Hertz' },
    seller_label: 'Riddhi S. (4th Yr BioMed)',
    verified: true,
    views: 310,
    created_at: '2 days ago'
  },
  {
    id: 'hce-06',
    user_id: 'u4',
    title: 'Resume Review & Mock Placement Interview Session',
    description: '4th Year IT student placed at Tier 1 Tech company. Will review your tech resume, ATS score formatting, and conduct 45-min mock technical interview.',
    price: 350,
    price_label: '₹ 350 / session',
    category: 'tutoring-services',
    condition: 'Brand new',
    campus: 'hce-mumbai',
    hostel: 'Harbour A',
    city: 'Mumbai, MH',
    image_url: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=800&q=80',
    featured: true,
    listing_kind: 'service',
    extra: { service: 'Resume & Interview Prep' },
    seller_label: 'Ananya M. (3rd Yr IT)',
    verified: true,
    views: 480,
    created_at: '1 day ago'
  },
  {
    id: 'hce-07',
    user_id: 'u4',
    title: 'LOST: Boat Airdopes 141 (Black Case) in Computer Lab 3',
    description: 'Left my earbud charging case in Lab 3 near Desktop PC-14 during 10 AM batch lab exam today. Please return if found!',
    price: 0,
    price_label: 'LOST ITEM',
    category: 'lost-found',
    condition: 'Fair',
    campus: 'hce-mumbai',
    hostel: 'Harbour B',
    city: 'Mumbai, MH',
    image_url: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?auto=format&fit=crop&w=800&q=80',
    featured: true,
    listing_kind: 'lostfound',
    extra: { status: 'LOST', item: 'Earbuds Case' },
    seller_label: 'Harsh T. (2nd Yr Comp)',
    verified: false,
    views: 190,
    created_at: '6 hours ago'
  },
  {
    id: 'hce-08',
    user_id: 'u4',
    title: 'Female Flatmate Wanted - 1BHK Marine PG (Near HCE Gate 1)',
    description: 'Looking for 1 female student to share spacious 1BHK PG near HCE main gate. Fully furnished, 24/7 water supply, security guard, Wi-Fi. Rent includes electricity.',
    price: 6000,
    price_label: '₹ 6,000 / month',
    category: 'roommates',
    condition: 'Like new',
    campus: 'hce-mumbai',
    hostel: 'Marine PG',
    city: 'Mumbai, MH',
    image_url: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=800&q=80',
    featured: true,
    listing_kind: 'roommate',
    extra: { occupancy: 'Double Sharing', gender: 'Female' },
    seller_label: 'Ananya M. (3rd Yr IT)',
    verified: true,
    views: 590,
    created_at: '2 days ago'
  }
];

export const CANNED_PINGS = [
  'Is this still available?',
  'Can we meet at the campus canteen today?',
  'What’s the final price for students?',
  'Can we meet near the Library / Main Gate today?',
  'Can I see it near the Dept / Hostel block this evening?'
];

export const INITIAL_LISTINGS = SEED_LISTINGS;
